# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages
r:
  - oldrel
  - release
  - devel

warnings_are_errors: false

r_github_packages:
  - sooheang/OutlierDM


after_success:
- Rscript -e 'covr::codecov()'
